config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :teams
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "hello#index"

  # Defines the root path route ("/")
  # root "articles#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true, length: {minimum: 8, maximum: 50}
  validates :title, presence: true, length: {minimum: 8, maximum: 50}
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :members
  has_many :users, through: :members
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :members
  has_many :teams, through: :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ root ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  # Create a Team Index
  def index
    # @teams = Team.all
  end

  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
    @member = Member.new
  end
  
  def edit
  end
  
  def create
    # @teams = Team.new(team_params)

    # respond_to do |format|
  end

  private
    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:name)
    end

end

app/controllers/turbo_devise_controller.rb
# ADDED this to fix user_url error, also configured devise.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/hello/index.html.erb
<div class="container">
  <h1>Hello, Tracks</h1>
</div>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% elsif alert %> 
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Tracks", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav ms-auto">
        <%= render 'user/session_manager' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# BOOTSTRAP CDN  %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <header>
        <%= render 'layouts/navbar' %>
      </header>

      <div class="container">
        <%= render 'layouts/alerts' %>
        <%= yield %>
      </div>
    </main>

    <%# BOOTSTRAP CDN JS %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr>
  <th scope="row"> 
    <%= project.id %> 
  </th>
  
  <td>
    <%= project.title %>
  </td>

  <td>
    <%= project.description %>
  </td>

  <td>
    <%= link_to "Show this project", project %>
  </td>

</tr>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Projects</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col"> # </th>
        <th scope="col"> Project </th>
        <th scope="col"> Description </th>
        <th scope="col"> Action </th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <%= render project %>
      <% end %>
    </tbody>

  </table>

  <%= link_to "New Project", new_project_path %>

</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="pane">
    <h2><%= @project.title %></h2>
    <p><%= @project.description %><p>
    <%=  @project.status %>
  </div>
  <div class="pane">
  </div>
  <div class="tasks-container">
  </div>
</div>

app/views/user/_session_manager.erb
<% if current_user %>
  <%# Show this if Current user is login %>
  <li class="nav-item">
    <%= link_to "Projects", projects_path, class:"nav-link active" %>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Profile
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
      <li><a class="dropdown-item" href="#">Notification</a></li>
      <li><a class="dropdown-item" href="#">Messages</a></li>
      <li><hr class="dropdown-divider"></li>
      <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
    </ul>
  </li>

<% else %>
  <%# Show this if User is not Login %>
  <li class="nav-item">
    <%= link_to "Create an Account", new_user_registration_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
  </li>

<% end %>